service: jisho-cards-services

provider:
  name: aws
  runtime: python3.6

functions:
  search:
    handler: search.handler
    events:
      - http:
          path: search
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
